# Sprint 1
CREATE DATABASE RESILIA;

USE RESILIA;

CREATE TABLE CURSO(
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
FRENTE VARCHAR(255)
);

CREATE TABLE TURMA (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CURSO INT,
    FOREIGN KEY (CURSO)
        REFERENCES CURSO (ID)
);
    
CREATE TABLE ALUNO (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(255),
    CPF VARCHAR(11),
    ID_TURMA INT,
    FOREIGN KEY (ID_TURMA)
        REFERENCES TURMA (ID)
);

CREATE TABLE FACILITADOR (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(255),
    FRENTE VARCHAR(255),
    ID_TURMA INT,
    FOREIGN KEY (ID_TURMA)
        REFERENCES TURMA (ID)
);

# Sprint 2
CREATE TABLE entregas (
    ID_ENTREGA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    link VARCHAR(500),
    modulo_projeto INT NOT NULL,
    id_aluno INT,
    FOREIGN KEY (id_aluno)
        REFERENCES aluno (ID),
    conceito VARCHAR(255)
);

ALTER TABLE aluno ADD email text;
